### ISSUE TITLE
[BUG] Debian package not released

### ISSUE THREAD

**Issue by MatthewForrester** [gfgit/ModelRailroadTimetablePlanner#60]
**Describe the bug**
Release 6.2.1 does not include the .deb file for Linux

**To Reproduce**
1. Go to [the release page for MRTP](https://github.com/gfgit/ModelRailroadTimetablePlanner/releases)
2. There is no .deb file for 6.2.x releases, though there was for 6.1.

**Expected behavior**
The .deb file is released for Linux users

**Desktop (please complete the following information):**
 n/a

**Additional context**
I just came across this package while searching for timetable planners. Thank you for writing it and releasing it under the GPL. :thumbsup:

**Comment by gfgit** [comment]
Hi, thank you for noticing!
I had problems with CMake's CPack not generating package description but then I forgot to upload the package.
Now it should be visible.
If you have any feedback/suggestion please let me know!

Filippo
